from __future__ import annotations

from typing import Any, Protocol


class SearchBackend(Protocol):
    """Interface for a search index backend, implemented by OpenSearchClient."""

    def available(self) -> bool: ...

    def wait_available(self, timeout_sec: int = 120) -> bool: ...

    def search(self, index: str, body: dict[str, Any]) -> dict[str, Any]: ...

    def bulk_index(self, index: str, docs: list[dict[str, Any]], chunk_size: int = 500) -> None: ...

    def create_index(self, index: str, body: dict[str, Any]) -> None: ...

    def delete_index(self, index: str) -> None: ...

    def update_cluster_settings(self, body: dict[str, Any]) -> None: ...
